apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cookbook
  name: cookbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cookbook
  template:
    metadata:
      labels:
        app: cookbook
    spec:
      containers:
      - image: tmp:cookbook
        name: cookbook
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SPRING_AI_OLLAMA_BASE_URL
          value: http://ollama:11434/
        - name: SPRING_AI_OLLAMA_CHAT_OPTIONS_MODEL
          valueFrom:
            configMapKeyRef:
              name: ollama
              key: model
